phases:
- phase: LinuxMono
  queue: Hosted Linux Preview
  steps:
  - bash: . 'build/install-mono.sh'
    displayName: Install Mono
  - bash: . 'build/cibuild.sh' '-hostType mono' 
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests*.xml'
    condition: always()

- phase: LinuxCoreCLR
  queue: Hosted Linux Preview
  steps:
  - bash: . 'build/cibuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests*.xml'
    condition: always()
