phases:
- phase: LinuxMono
  queue: Hosted Linux Preview
  steps:
  - script: |
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    apt install apt-transport-https
    echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | tee /etc/apt/sources.list.d/mono-official-stable.list
    apt update
    
    apt install mono-devel
      
    displayName: Command Line Script
  - bash: . 'build/cibuild.sh' '-hostType mono' 
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests*.xml'
    condition: always()

- phase: LinuxCoreCLR
  queue: Hosted Linux Preview
  steps:
  - bash: . 'build/cibuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests*.xml'
    condition: always()
