phases:
- phase: Mac Mono
  queue: Hosted macOS Preview
  steps:
  - bash: . 'build/cibuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests*.xml'
    condition: always()

- phase: Linux CoreCLR
  queue: Hosted Linux Preview
  steps:
  - bash: . 'build/cibuild.sh'
    displayName: CI Build
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testRunner: XUnit
      testResultsFiles: 'artifacts/**/*UnitTests*.xml'
    condition: always()
